user admin
topic readwrite #

user laravel_backend
topic read gps/devices/+/telemetry
topic read gps/devices/+/status
topic read gps/devices/+/cmd_res
topic write gps/commands/#
topic read $SYS/#
topic write gps/events/stats

pattern write gps/devices/%u/telemetry
pattern write gps/devices/%u/status
pattern write gps/devices/%u/cmd_res
pattern read gps/commands/%u/+


user simulator
topic write gps/devices/+/telemetry
topic write gps/devices/+/status
