[program:mqtt-subscriber]
process_name%(program_name)s_%(process_num)02d
#El comando exacto que queremos mantener vivo
command=php /var/www/html/artisan mqtt:subscribe

#1. Auto-reinicio
autorestart=true
autorestart=true

#2. Limites de reintentos
startretries=5

#3. Configuracion de cierre seguro
stopasgroup=true
killasgroup=true
stopwaitsecs=10

#4. Logging
redirect_stderr=true
stdout_logfile=/var/log/supervisor/mqtt-subscriber.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2